export const ContactusStyledNew = (theme) => ({
  footer: {
    backgroundColor: theme.palette.background.primary.main,
    marginTop: "3%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
    height: "285px",
    width: "100%",
  },
  footercontents: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    color: theme.palette.text[50],
    justifyContent: "space-evenly",
    height: "100%",
    width: "100%",
  },
  leftfooter: {
    backgroundImage: 'url("/src/assets/LeftFooter.svg")',
    backgroundRepeat: "no-repeat",
    height: "100%",
    position: "absolute",
    top: "0",
    left: "0",
    width: "27%",
  },
  rightfooter: {
    backgroundImage: 'url("/src/assets/RightFooter.svg")',
    backgroundRepeat: "no-repeat",
    height: "100%",
    position: "absolute",
    top: "0",
    right: "0",
    width: "27%",
  },
  maildetails: {
    display: "flex",
    height: "52px",
    width: "322px",
    justifyContent: "center",
  },
  mailcontainer: {
    display: "flex",
    backgroundColor: theme.palette.background.knowmore,
    alignItems: "center",
    width: "85%",
    justifyContent: "space-evenly",
  },
  mailto: {
    fontFamily: theme.palette.fontfamily.dm_sans,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.palette.text[800],
    padding: "1%",
    fontSize: theme.palette.fontsize.verysmall,
    fontWeight: theme.palette.fontweight.thickbold,
    width: "58px",
    textAlign: "center",
    backgroundColor: theme.palette.background.mailto,
  },
  mail: {
    fontFamily: theme.palette.fontfamily.dm_sans,
    fontSize: theme.palette.fontsize.large,
  },
  mailarrow: {
    backgroundColor: theme.palette.background.arrow,
    display: "flex",
    alignItems: "center",
    width: "15%",
    justifyContent: "center",
    textAlign: "center",
    cursor: "pointer",
  },
  contactus: {
    fontFamily: theme.palette.fontfamily.ibm_plex,
    fontSize: theme.palette.fontsize.verylarge,
    fontWeight: theme.palette.fontweight.thickbold,
  },
  ques: {
    fontFamily: theme.palette.fontfamily.dm_sans,
    fontSize: theme.palette.fontsize.small,
    fontWeight: theme.palette.fontweight.normal,
  },
  help: {
    fontFamily: theme.palette.fontfamily.dm_sans,
    fontSize: theme.palette.fontsize.small,
  },
});
