import { margin } from "@mui/system";

export const OurteamStyledNew = (theme) => ({
  swiper: {
    width: "100%",
    padding: "20px 0",
  },
  swipercomSmall: {
    padding: "0% 0% 0% 0%",
    backgroundColor: "#f9f9f9",
  },
  swipercom: {
    padding: "0% 10% 0% 0%",
  },
  swiperslide: {
    height: "100%",
    width: "100%",
  },
  parallelogramContainer: {
    height: "407px",
    position: "relative",
    width: "83%",
    margin: "0 auto",
    transform: "skew(-25deg)",
    backgroundColor: "#f9f9f9",
    borderRadius: "0px",
    overflow: "hidden",
    boxShadow: "none",
    display: "flex",
    "@media (max-width: 600px)": {
        justifyContent: "space-evenly",
      transform: "skew(0deg)",
      display: "flex",
      flexDirection: "column",
      height: "100%",
    },
  },
  parallelogramContainerSmall: {
    position: "relative",
    margin: "0 auto",
    backgroundColor: "#f9f9f9",
    borderRadius: "0px",
    overflow: "hidden",
    boxShadow: "none",
    display: "flex",
    padding: "3%",
    transform: "skew(0deg)",
    flexDirection: "column",
    height: "100%",
    width: "100%",
    justifyContent: "space-evenly",
  },
  parallelogramImage: {
    width: "304px",
    height: "334px",
    marginTop: "auto",
    marginLeft: "3%",
    zIndex: "2",
    transform: "skew(25deg)",
  },
  parallelogramImageSmall: {
    width: "304px",
    height: "250px",
    // marginTop: "auto",
    marginLeft: "3%",
    zIndex: "1",
    transform: "skew(0deg)",
  },
  parallelogramContent: {
    color: "#333",
    width: "60%",
    marginTop: "3%",
    backgroundColor: "#f9f9f9",
    transform: "skew(25deg)",
    textAlign: "left",
    position: "relative",
    display: "flex",
    "@media (max-width: 600px)": {
      transform: "skew(0deg)",
      width: "93%",
      flexDirection: "column",
      gap: "1rem"
    },
  },

  contentParagraph: {
    fontSize: "14px",
    color: theme.palette.text[600],
    fontFamily: "DM_sans",
  },
  subteam: {
    backgroundColor: "#009065",
    color: theme.palette.text[50],
    width: "345px",
    height: "60px",
    position: "absolute",
    bottom: "5%",
    left: "33%",
    transform: "skewX(-30deg)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    zIndex: "1",
  },
  subteamSmall: {
    backgroundColor: "#009065",
    color: theme.palette.text[50],
    width: "345px",
    height: "60px",
    transform: "skewX(-40deg)",
    display: "flex",
    marginLeft: "-50px",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    
  },
  subteamcontent: {
    display: "flex",
    textAlign: "start",
    flexDirection: "column",
  },

  contentHeading: {
    margin: 0,
    fontSize: "18px",
    fontWeight: "bold",
    transform: "skew(40deg)",
    fontFamily: "IBM_Plex_Serif",
    "@media (max-width: 600px)": {
      transform: "skew(40deg)",
    },
  },
  contentSubHeading: {
    fontSize: "14px",
    fontWeight: "400",
    transform: "skew(40deg)",
    fontFamily: "DM_sans",
    "@media (max-width: 600px)": {
      transform: "skew(40deg)",
    },
  },
});
